"""product name search

Revision ID: 06f2295a322d
Revises: 0bb2b31ac6f8
Create Date: 2026-01-05 16:07:22.506139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f2295a322d'
down_revision = '0bb2b31ac6f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_search', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_product_name_search'), ['name_search'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_name_search'))
        batch_op.drop_column('name_search')

    # ### end Alembic commands ###
