"""usd rate

Revision ID: 0bb2b31ac6f8
Revises: d1e14e927faf
Create Date: 2025-12-12 11:52:04.817061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb2b31ac6f8'
down_revision = 'd1e14e927faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smm_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usd_rate', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smm_stats', schema=None) as batch_op:
        batch_op.drop_column('usd_rate')

    # ### end Alembic commands ###
