"""add unit margin to orderItem

Revision ID: 0d14a75e3983
Revises: 06f2295a322d
Create Date: 2026-01-20 10:59:25.015569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import DECIMAL
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '0d14a75e3983'
down_revision = '06f2295a322d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_margin', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
        batch_op.alter_column(column_name='unit_price', server_default="0")

    op.execute(text("""
                    UPDATE order_item
                    SET unit_margin = COALESCE(
                            (SELECT ROUND(order_item.unit_price - p.cost, 2)
                             FROM product p
                             WHERE p.id = order_item.product_id),
                            0
                                      )
                    """))

    with op.batch_alter_table("order_item") as batch_op:
        batch_op.alter_column("unit_margin", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('unit_margin')

    # ### end Alembic commands ###
