"""add unit_name to orderItem

Revision ID: 4f10aa6965ce
Revises: 0d14a75e3983
Create Date: 2026-01-20 13:09:21.299575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '4f10aa6965ce'
down_revision = '0d14a75e3983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_name', sa.String(length=100), nullable=False, server_default='[deleted]'))

    op.execute(text("""
                    UPDATE order_item
                    SET unit_name = COALESCE(
                            (SELECT p.name FROM product p WHERE p.id = order_item.product_id),
                            '[deleted]'
                                    )
                    """))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('unit_name')

    # ### end Alembic commands ###
