"""add OrderItem unit_name_search

Revision ID: 9f11d63229e7
Revises: 4f10aa6965ce
Create Date: 2026-01-20 14:47:08.115938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f11d63229e7'
down_revision = '4f10aa6965ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_name_search', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_item_unit_name_search'), ['unit_name_search'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_item_unit_name_search'))
        batch_op.drop_column('unit_name_search')

    # ### end Alembic commands ###
