"""add SMMStats

Revision ID: d1e14e927faf
Revises: c43f98efe2ce
Create Date: 2025-11-07 12:53:00.433254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e14e927faf'
down_revision = 'c43f98efe2ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smm_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('spends', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('coverage', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('direct_messages', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smm_stats')
    # ### end Alembic commands ###
